export const STATIC_CONTENT_CREATE_SUCCESS = "Static content create successfully.";
export const STATIC_CONTENT_LIST_SUCCESS = "Static content list found successfully.";
export const STATIC_CONTENT_UPDATE_SUCCESS = "Static content updated successfully.";
export const STATIC_TITLE_REQUIRED = "Title is required.";
export const STATIC_TITLE_MAX_LENGTH = "Title can not be greater than 100 characters.";
export const STATIC_DESCRIPTION_REQUIRED = "Description is required.";
export const STATIC_DESCRIPTION_MAX_LENGTH = "Description can not be greater than 5000 characters.";
export const STATIC_SHORT_DESCRIPTION_REQUIRED = " Short Description is required.";
export const STATIC_SHORT_DESCRIPTION_MAX_LENGTH = "Short Description can not be greater than 5000 characters.";
